# Generated by Django 4.2.5 on 2023-09-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='meta',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='test',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
